---
title: "Inquiline Genomics: Final Figures: Reconciled Clade 285"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    number_sections: true
    df_print: paged
  pdf_document: default
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>
```{r}

source("~/sciebo/librarySchrader.R")
library(plyr)
library(tidyr)
require(ggtree)
require(phylobase)
require(phytools)
library(viridis)
library(ggplot2)
library(extrafont)
library(ape)
library(plotrix)
#install.packages("devtools")
#library(devtools)
#install_github("PuttickMacroevolution/MCMCTreeR",force=T)
library(MCMCtreeR)

# define function for desaturating colors
desat <- function(cols, sat=0.5) {
    X <- diag(c(1, sat, 1)) %*% rgb2hsv(col2rgb(cols))
    hsv(X[1,], X[2,], X[3,])
}

```

Add node labels before running ranger-dtl
```{r}

tree<-read.tree(file = "/Users/lukas/sciebo/Projects/testing/tmp/dlcpar/9E-Clade-285.FT.tre")

```

# adopt dlc reconciliation
```{r}
tree$node.label

m2Node<-read.csv("/Users/lukas/sciebo/Projects/testing/tmp/dlcpar/9E-Clade-285.FT.tre.dlcsearch.locus.recon",sep="\t",F)
colnames(m2Node)<-c("Node","speciesNode","type")
#m2Node<-m2Node[order(as.numeric(gsub("NODE_","",m2Node$V2))),]
#tree$node.label<-m2Node$V1

```

```{r}
#tree$node.label<-as.character(tree$node.label)
g2 = as(tree, 'phylo4')
#g2 = phylo4d(g1)

tipLabels(g2)<-gsub("(.*?-.*)-.*","\\1",tipLabels(g2),perl=T)


g3<-ggtree(g2, size=.5,ladderize=T,right = F,lineend="square") +  
  geom_tiplab(size = 1.5, col ="black",align = F,linetype = "dotted",linesize=.25, offset=.002) +
  geom_rootedge(.005,size=.5,color="black")+ 
  geom_treescale(x=0.01,y=77,fontsize=2.5,width=.02)
  
```
```{r}
#recon<-read.csv("/Users/lukas/sciebo/Projects/testing/tmp/ranger/reconciliation.tsv",sep="\t",skip=1,F)

tmp<-merge(g3$data,m2Node,by.x="label",by.y="Node",all.x=T)
g3$data<-tmp
tmp[tmp$isTip==F,]
```

```{r}
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="1"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="2"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="3"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="4"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="5"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="TZET"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="TSEP"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="TCOR"]<-"other"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="CCOS"]<-"other"

levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="ACOL"]<-"Atta"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="ACEP"]<-"Atta"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="10"]<-"Atta"

levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="6"]<-"Acromyrmex"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="7"]<-"Acromyrmex"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="AHEY"]<-"Acromyrmex"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="AECH"]<-"Acromyrmex"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="9"]<-"Acromyrmex"

levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="PARG"]<-"Parasites"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="ACHA"]<-"Parasites"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="AINS"]<-"Parasites"
levels(g3$data$speciesNode)[levels(g3$data$speciesNode)=="8"]<-"Parasites"
g3$data$speciesNode[is.na(g3$data$speciesNode)]<-"other"



subsetting<-levels(g3$data$speciesNode)[!levels(g3$data$speciesNode)%in% c("ACEP","ACHA","ACOL","AECH","AHEY","AINS","CCOS","PARG","TCOR","TSEP","TZET")]
g3+geom_point2(aes(col=speciesNode,pch=type,subset=isTip==F),size=2)+ geom_label(aes(x=branch, label=label),size=1,label.size = 0,fill=rgb(0,0,0,0),vjust=-.5,col="red")

```

# add manually inferred losses
```{r}
losses<-read.csv("/Users/lukas/sciebo/Projects/testing/tmp/dlcpar/inferredLosses2.tsv",sep="\t",F)
colnames(losses)<-c("node","loss")

losses$lossgroup<-losses$loss
levels(losses$lossgroup)<-rep("Deletions",3)
tmp<-merge(g3$data,losses,by.x="label",by.y="node",all.x=T)
g3$data<-tmp

```

```{r}
g4<-g3+geom_point2(aes(x=branch,fill=lossgroup,subset=!is.na(loss)),size=2,pch=23)+
  scale_fill_manual(values=goodCols[3],guide=F)+
  geom_point2(aes(col=speciesNode,pch=type,subset=isTip==F ),size=2)+
  scale_color_manual(values=c("grey60","lightblue",goodCols[c(1,3)]))+
  scale_shape(labels=c("Duplication","Speciation","Deletion (parasite)"))+
  guides(color = guide_legend(order = 1),
         shape = guide_legend(override.aes = list(shape = c(1,2,23),fill=c(NULL,NULL,goodCols[3]))))+
  labs(color = "Group",pch="Event")+
    theme(legend.position = c(0.15,0.75),legend.spacing.y = unit(-0.02, 'cm'),legend.key=element_blank())

```
```{r}
g5<-g4+  geom_hilight(node=g4$data$node[g4$data$label=="NODE_8"], fill="lightblue", alpha=0.1,extend = .035) +  geom_hilight(node=g4$data$node[g4$data$label=="NODE_13"], fill=goodCols[1], alpha=0.1,extend = .035) +
    geom_cladelabel(node=g4$data$node[g4$data$label=="NODE_8"], "italic('Atta')~expansion", offset=.03, barsize=0, angle=90, offset.text=0.002, hjust=0, fontsize=3,parse=T)+geom_cladelabel(node=g4$data$node[g4$data$label=="NODE_13"], "italic('Acromyrmex')~expansion", offset=.03, barsize=0, angle=90, offset.text=0.002, hjust=.2, fontsize=3,parse=T) 

g5$layers<-g5$layers[c(9:14,1:8)]
```

```{r}

g5+ theme(legend.key.height=unit(.6,"line"),legend.key.width = unit(.5,"line"))
dev.print(pdf,"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/reconciliation/9E-Clade285.reconciled.pdf",width=4,height=7)
```
<!--
```{r}
d<-data.frame(cbind (g3$data$label,substr(g3$data$label,1,4)))
colnames(d)<-c("tip","species")
rownames(d)<-d$tip
d$parasite<-"nonLC"
d$parasite[d$species=="Parg"|d$species=="Acha"|d$species=="Ains"]<-"P"
d$parasite[d$species=="Acol"|d$species=="Acep"]<-"Atta"
d$parasite[d$species=="Ahey"|d$species=="Aech"]<-"Acromyrmex"
d$tip<-NULL
d$species<-NULL
g4<-gheatmap(g3, d, offset = -0.1, width=0.2,colnames=F) + 
  scale_fill_manual(values=c(goodCols[1],desat(goodCols[1],.6),"gray60",goodCols[3])) +
  theme(legend.position="none")

```

