---
title: "Inquiline Genomics: analysis and summary of absREL"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    number_sections: true
    df_print: paged
  pdf_document: default
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>

# Input data 
### Load environment
```{r}
#install.packages("rjson")
library("rjson")
library(plyr)
library(tidyr)
```

### Locate data
```{r}
folder<-"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/OR.SOS/absREL/"
files<-dir(folder,pattern =".json")
```

### Retrieve branch wide dN/dS estimates for all SCOs
```{r}

# branch-wise dN/dS rates
omegas<-list()

# gene names for each OG
branchNames<-list()

# pvalues for each branch and OG
pvalues<-list()

# other metric (currently branch lengths)
others<-list()

# dN rates (improper)
dNs<-list()

# dS rates (improper)
dSs<-list()

# all jsons
results<-list()

# loop over json file from each SCO and retrieve data. Store data in data frames 
for (q in 1:length(files)){
  OG<-gsub(pattern="(^.+?)\\.aln.*","\\1",perl=T,x=files[q])
  result <- fromJSON(file = paste(folder,files[q],sep=""))
  results[[q]]<-result
  names(results)[q]<-OG
  omega<-NA
  pvals<-NA
  other<-NA
  dN<-NA
  dS<-NA
  for (i in 1:length(result$`branch attributes`$`0`)){
    if(length(result$`branch attributes`$`0`[[i]])==1){next}
    omega[i]<-result$`branch attributes`$`0`[[i]]$`Baseline MG94xREV omega ratio`
    pvals[i]<-result$`branch attributes`$`0`[[i]]$`Corrected P-value`
    other[i]<-result$`branch attributes`$`0`[[i]]$`Baseline MG94xREV`
    dN[i]<-result$`branch attributes`$`0`[[i]]$`Rate Distributions`[[1]][1]
    dS[i]<-result$`branch attributes`$`0`[[i]]$`Rate Distributions`[[1]][2]
    names(omega)[i]<-names(result$`branch attributes`$`0`)[i]
    names(pvals)[i]<-names(result$`branch attributes`$`0`)[i]
    names(other)[i]<-names(result$`branch attributes`$`0`)[i]
    omegas[[OG]]<-omega
    pvalues[[OG]]<-pvals
    others[[OG]]<-other
    dNs[[OG]]<-dN
    dSs[[OG]]<-dS
    
  }
  names(pvalues[[OG]])<-names(pvals)
  names(others[[OG]])<-names(other)
  branchNames[[OG]]<-names(omega)
  names(omegas[[OG]])<-names(omega)

}
```

```{r}
m1<-stack(lapply(pvalues,names))
m2<-stack(pvalues)
m3<-data.frame(cbind(m1,m2$values),stringsAsFactors = F)
colnames(m3)<-c("branch","clade","pvalue")
m3$pvalue<-as.numeric(m3$pvalue)
m3$fdr<-p.adjust(m3$pvalue,'fdr')
m3$sf<-as.factor(gsub("-.*","",m3$clade))
```

```{r}
sum(grepl("Ains",subset(m3,fdr<0.05)$branch))
sum(grepl("Parg",subset(m3,fdr<0.05)$branch))
barplot(summary(subset(m3,fdr<0.05)$sf),las=2)
cladeSig<-subset(m3,fdr<0.05,clade)
barplot(table(cladeSig$clade)/table(m3$clade),las=2,cex.names = .4)

sfSig<-subset(m3,fdr<0.05)
barplot(table(sfSig$sf)/table(m3$sf),las=2,cex.names = .4)

m3$sig<-as.factor(ifelse(m3$fdr<0.05,"1","0"))

library(ggplot2)
source("~/sciebo/librarySchrader.R")

dat<-cbind(data.frame(table(sfSig$sf)/table(m3$sf)),table(sfSig$sf),table(m3$sf))
dat<-dat[,c(1,2,4,6)]

colnames(dat)<-c("Subfamily","Freq","selected","total")
p<-ggplot(data=dat,aes(x=Subfamily,y=Freq)) + geom_bar(stat="identity") + ylab("Frequency of branches under positive selection\n within subfamily clades (fdr<0.05)") + geom_text(aes(label=selected), vjust=1.6, color="white", size=3.5) +  geom_text(aes(label=total), vjust=-0.3, size=2) + theme_minimal()
p

```


```{r}
PargOM<-unlist(lapply(omegas,function(x) x[grep("Parg",names(x),value = T)]))
AheyOM<-unlist(lapply(omegas,function(x) x[grep("Ahey",names(x),value = T)]))
AchaOM<-unlist(lapply(omegas,function(x) x[grep("Acha",names(x),value = T)]))
AechOM<-unlist(lapply(omegas,function(x) x[grep("Aech",names(x),value = T)]))
AinsOM<-unlist(lapply(omegas,function(x) x[grep("Ains",names(x),value = T)]))
boxplot(PargOM,AheyOM,AechOM,AchaOM,AinsOM,outline=F)
```

### Create dataframes
```{R}
# dN/dS
max(lengths(omegas))
for(i in 1:length(omegas)){
  length(omegas[[i]])<-max(lengths(omegas))
}
om<-do.call(rbind,omegas)

# branch names
max(lengths(branchNames))
for(i in 1:length(branchNames)){
  length(branchNames[[i]])<-max(lengths(branchNames))
}
bn<-do.call(rbind,branchNames)

# pvalues
max(lengths(pvalues))
for(i in 1:length(pvalues)){
  length(pvalues[[i]])<-max(lengths(pvalues))
}
pv<-do.call(rbind,pvalues)

# other
max(lengths(others))
for(i in 1:length(others)){
  length(others[[i]])<-max(lengths(others))
}
ot<-do.call(rbind,others)

# dN
max(lengths(dNs))
for(i in 1:length(dNs)){
  length(dNs[[i]])<-max(lengths(dNs))
}
dn<-do.call(rbind,dNs)

# dS
max(lengths(dSs))
for(i in 1:length(dSs)){
  length(dSs[[i]])<-max(lengths(dSs))
}
ds<-do.call(rbind,dSs)

colnames(om)<-paste("om",1:dim(om)[2],sep="")
colnames(bn)<-paste("bn",1:dim(bn)[2],sep="")
colnames(pv)<-paste("pv",1:dim(pv)[2],sep="")
colnames(dn)<-paste("dn",1:dim(dn)[2],sep="")
colnames(ds)<-paste("ds",1:dim(ds)[2],sep="")
colnames(ot)<-paste("ot",1:dim(ot)[2],sep="")
### create one big data frame
allABSREL<-cbind(om,bn,pv,dn,ds,ot)
head(allABSREL)
#allABSREL$OGid<-row.names(allABSREL)
#allABSREL

```



```{r}
oMeans<-unlist(lapply(omegas,function(x) median(x,na.rm=T)))
oMsf<-split(oMeans,f=gsub("-.*","",names(oMeans)))

# distribution of median omega rates in 9E clades
boxplot(oMsf$`9E`,unlist(oMsf[names(oMsf)[-1]]),outline=F,names=c("9E","other"))

# distribution of omega rates in branches of 9E 
allOm<-split(unlist(omegas),f=gsub("-.*","",names(unlist(omegas))))
boxplot(allOm$`9E`,unlist(allOm[names(allOm)[-1]]),outline=F,names=c("9E","other"))
wilcox.test(allOm$`9E`,unlist(allOm[names(allOm)[-1]]))

boxplot(allOm,outline=F,ylim=c(0,4))

# significantly higher dN/dS rates in 9E family branches
f1<-rep("E",length(allOm$`9E`))
f2<-rep("O",length(unlist(allOm[names(allOm)[-1]])))
v1<-allOm$`9E`
v2<-unlist(allOm[names(allOm)[-1]])
boxplot(v1,v2,outline=F)
f<-as.factor(c(f1,f2))
library(coin)
wilcox_test(c(v1,v2)~f,distribution = approximate(nresample = 10000))


v1<-(allOm$`9E`[grep("Parg",names(allOm$`9E`))])
v2<-(allOm$`9E`[grep("Ahey",names(allOm$`9E`))])
v3<-(allOm$`9E`[grep("Acha",names(allOm$`9E`))])
v4<-(allOm$`9E`[grep("Ains",names(allOm$`9E`))])
v5<-(allOm$`9E`[grep("Aech",names(allOm$`9E`))])
v6<-(allOm$`9E`[grep("Acol",names(allOm$`9E`))])

o1<-allOm$E[grep("Parg",names(allOm$E))]
o2<-(allOm$E[grep("Ahey",names(allOm$E))])
o3<-(allOm$E[grep("Acha",names(allOm$E))])
o4<-(allOm$E[grep("Ains",names(allOm$E))])
o5<-(allOm$E[grep("Aech",names(allOm$E))])
o6<-(allOm$E[grep("Acol",names(allOm$E))])

boxplot(v1,v2,v3,v4,v5,v6,o1,o2,o3,o4,o5,o6,outline=F,names=rep(c("Parg","Ahey","Acha","Ains","Aech","Acol"),2),las=2)
```

