---
title: "Inquiline Genomics: analysis and summary of absREL of odorant receptor genes"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    number_sections: true
    df_print: paged
  pdf_document: default
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>

# Input data 
### Load environment
```{r}
#install.packages("rjson")
source("~/sciebo/librarySchrader.R")
library(ggplot2)
library(jmuOutlier)
library("rjson")
library(plyr)
library(tidyr)
library(coin)
```

### Locate data
```{r}
folder<-"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/OR.SOS/absREL/"
files<-dir(folder,pattern =".json")
```

### Retrieve branch wide dN/dS estimates for all SCOs
```{r}

# branch-wise dN/dS rates
omegas<-list()

# gene names for each OG
branchNames<-list()

# pvalues for each branch and OG
pvalues<-list()

# other metric (currently branch lengths)
others<-list()

# dN rates (improper)
dNs<-list()

# dS rates (improper)
dSs<-list()


# loop over json file from each SCO and retrieve data. Store data in data frames 
for (q in 1:length(files)){
  OG<-gsub(pattern="(.+?)\\..*","\\1",perl=T,x=files[q])
  result <- fromJSON(file = paste(folder,files[q],sep=""))
  
  omega<-NA
  pvals<-NA
  other<-NA
  dN<-NA
  dS<-NA
  for (i in 1:length(result$`branch attributes`$`0`)){
    #if(length(result$`branch attributes`$`0`)==2){next()}
    if(length(result$`branch attributes`$`0`[[i]]$`Baseline MG94xREV omega ratio`)==1){
    omega[i]<-result$`branch attributes`$`0`[[i]]$`Baseline MG94xREV omega ratio`
    pvals[i]<-result$`branch attributes`$`0`[[i]]$`Corrected P-value`
    other[i]<-result$`branch attributes`$`0`[[i]]$`Baseline MG94xREV`
    dN[i]<-result$`branch attributes`$`0`[[i]]$`Rate Distributions`[[1]][1]
    dS[i]<-result$`branch attributes`$`0`[[i]]$`Rate Distributions`[[1]][2]
    }else{
      omega[i]<-NA
      pvals[i]<-NA
      other[i]<-NA
    }
    names(omega)[i]<-names(result$`branch attributes`$`0`)[i]
    names(pvals)[i]<-names(result$`branch attributes`$`0`)[i]
    names(other)[i]<-names(result$`branch attributes`$`0`)[i]
    names(dN)[i]<-names(result$`branch attributes`$`0`)[i]
    names(dS)[i]<-names(result$`branch attributes`$`0`)[i]
    omegas[[OG]]<-omega
    pvalues[[OG]]<-pvals
    others[[OG]]<-other
    dNs[[OG]]<-dN
    dSs[[OG]]<-dS
  }
  names(pvalues[[OG]])<-gsub(x=names(pvals),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  names(others[[OG]])<-gsub(x=names(pvals),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  branchNames[[OG]]<-names(omega)
  names(omegas[[OG]])<-gsub(x=names(omega),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  names(dNs[[OG]])<-gsub(x=names(dN),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  names(dSs[[OG]])<-gsub(x=names(dS),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  names(branchNames[[OG]])<-gsub(x=names(omega),pattern="([A-Z]{4})[0-9]{5}","\\1",perl=T)
  reorder<-order(names(omegas[[OG]]))
  
  omegas[[OG]]<-omegas[[OG]][reorder]
  pvalues[[OG]]<-pvalues[[OG]][reorder]
  branchNames[[OG]]<-branchNames[[OG]][reorder]
  others[[OG]]<-others[[OG]][reorder]
}
```

### Create dataframes
```{R}
# dN/dS
om <- do.call("c", omegas)
# branch names
bn <- do.call("c", branchNames)
# pvalues
pv <- do.call("c", pvalues)
# other
ot <- do.call("c", others)
# dN
dn <- do.call("c", dNs)
# dS
ds <- do.call("c", dSs)

#dN/(dN+dS)
rate<-dn/(dn+ds)
```

```{r}
boxplot(rate[grep("Ccos|Tzet|Tsep|Tcor",names(rate))],rate[grep("Acep|Acol|Aech|Ahey",names(rate))],rate[grep("Ains|Acha|Parg",names(rate))],outline=F)

rLC<-rate[grep("Acep|Acol|Aech|Ahey",names(rate))]
rP<-rate[grep("Ains|Acha|Parg",names(rate))]
rNLC<-rate[grep("Ccos|Tzet|Tsep|Tcor",names(rate))]

df<-data.frame(rate=c(rP,rLC,rNLC),type=c(rep("P",length(rP)),rep("LC",length(rLC)),rep("NLC",length(rNLC))))
df$type<-factor(df$type,levels=levels(df$type)[c(2,1,3)])
#df<-data.frame(rate=c(rP,rLC),type=c(rep("P",length(rP)),rep("LC",length(rLC))))
pairwise.wilcox.test(df$rate,df$type,p.adjust.method = "bonferroni")
perm.test(rP[!is.na(rP)],rLC[!is.na(rLC)],stat=median,paired=F)
perm.test(rP[!is.na(rP)],rNLC[!is.na(rNLC)],stat=median,paired=F)
perm.test(rNLC[!is.na(rNLC)],rLC[!is.na(rLC)],stat=median,paired=F)
```

### Permuted two-sample (paired) wilcoxon tests
```{r}
backgroundWT.PvsLC<-coin::wilcox_test(rate~type,data=subset(df,type=="P"|type=="LC"),paired=F,distribution = approximate(nresample=20000))
backgroundWT.NLCvsLC<-coin::wilcox_test(rate~type,data=subset(df,type=="NLC"|type=="LC"),paired=F,distribution = approximate(nresample=20000))
backgroundWT.PvsNLC<-coin::wilcox_test(rate~type,data=subset(df,type=="P"|type=="NLC"),paired=F,distribution = approximate(nresample=20000))

backgroundWT.PvsLC.corrected<-pvalue(backgroundWT.PvsLC)*3
backgroundWT.NLCvsLC.corrected<-pvalue(backgroundWT.NLCvsLC)*3
backgroundWT.PvsNLC.corrected<-pvalue(backgroundWT.PvsNLC)*3
```

```{r fig.height=3, fig.width=3}
ggplot(df,aes(y=rate,x=type,fill=type))+
    geom_boxplot(notch=TRUE,outlier.shape=NA)+scale_fill_manual(values=goodCols[1:3]) + theme_classic() + theme(legend.position = "none") + ylim(c(0,1)) + theme(plot.margin=unit(c(1,0,0,0),"cm"))+ scale_y_continuous(breaks=c(0,0.5,1)) + 
  geom_segment(aes(x=1,y=1.05,xend=2,yend=1.05),lwd=.1) +
  geom_segment(aes(x=2,y=1.2,xend=3,yend=1.2),lwd=.1) +
  geom_segment(aes(x=1,y=1.35,xend=3,yend=1.35),lwd=.1) + 
  annotate(geom="text",x=1.5, y=1.12, label=paste("p=",backgroundWT.NLCvsLC.corrected[1],sep=""),size=2) +
  annotate(geom="text",x=2.5, y=1.252, label=paste("p=",backgroundWT.PvsLC.corrected[1],sep=""),size=2) +
  annotate(geom="text",x=2, y=1.42, label=paste("p=",backgroundWT.PvsNLC.corrected[1],sep=""),size=2)


ggplot(df,aes(x=type,y=rate, fill=type)) +   geom_violin(alpha=.2,lwd=0)+ scale_fill_manual(values = c(goodCols[1],goodCols[1],goodCols[3])) + theme_classic()+ geom_boxplot(width=.1,notch=T,outlier.shape = NA,lwd=.3)+theme(legend.position = "none")+annotate(geom="text",x=c(1:3),y=rep(1.1,3),label=c("a","a","b"))

ggplot(df,aes(x=type,y=rate, fill=type)) +   geom_violin(alpha=.2,lwd=0)+ scale_fill_manual(values = c(goodCols[1],goodCols[1],goodCols[3])) + theme_classic()+ geom_boxplot(width=.4,notch=T,outlier.shape = NA,lwd=.3)+theme(legend.position = "none")+annotate(geom="text",x=c(1:3),y=rep(1.1,3),label=c("a","a","b"))+coord_cartesian(ylim=c(0,0.75))


dev.print(pdf,"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/OR.SOS/results/absREL.ORs.pdf",width=2,height=3)
```
```{r}

```

```{r}

df2<-subset(df,type!="NLC")
ggplot(df2, aes(x=rate,group=type,fill=type)) + scale_fill_manual(values=goodCols[2:3]) + 
    geom_histogram(aes(y=0.05*..density..),
                 alpha=.5,binwidth=0.5,color=1,position="dodge")

#ggplot(df2,aes(group=type,x=rate))+
#  geom_density()+
#  scale_fill_manual(values=goodCols[1:3]) + theme_classic() + theme(legend.position = "bottom")+scale_y_continuous(trans='log2') + ylim(c(0,1))

#dev.print(pdf,"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/OR.SOS/results/absREL.ORs2.pdf",width=2,height=3)

```


