---
title: "Plot complex tree of ORs in inquilines"
output: html_notebook
---

```{r}
######################
# Load packages
######################
library("ape")
library("Biostrings")
library("ggplot2")
library("ggtree")
library("phytools")
library("treeman")
library(diversitree)
library(phytools)
library(geiger)
library(cowplot)
```


```{r}
############################################
# Load rerooted FastTree tree
############################################
t1<-read.tree("/Users/lukas/sciebo/inquilineGenomics18/ORevolution/results/tree/ant.OR.rooted.tre")
#tree <- as(t1, 'TreeMan')

```

```{r}
############################################
# Load subfam assignments
############################################

subfam<-read.table("/Users/lukas/sciebo/inquilineGenomics18/ORevolution/results/tree/ORsubfamily.assignment.tsv",sep="\t")

```

```{r}
classSubfam<-as.character(subfam$V2)
names(classSubfam)<-subfam$V1
```

```{r}

############################################
# Generate clades
############################################
cladesTree<-getCladesofSize(t1,11)

cladeSizes<-NA
traits<-rep(NA,length(t1$tip.label))
traits2<-rep(NA,length(t1$tip.label))
traits3<-rep(NA,length(t1$tip.label))
names(traits)<-t1$tip.label
names(traits2)<-t1$tip.label
names(traits3)<-t1$tip.label
for(i in 1:length(cladesTree)){
  cladeSizes[i]<-(length(cladesTree[[i]]$tip.label))
  # check if clade contains Parg
  if (length(grep("Ahey",cladesTree[[i]]$tip.label))>length(grep("Aech",cladesTree[[i]]$tip.label))){
    traits[cladesTree[[i]]$tip.label]<-1
  }else{
    traits[cladesTree[[i]]$tip.label]<-0
  }
  if (length(grep("Ahey",cladesTree[[i]]$tip.label))>length(grep("Parg",cladesTree[[i]]$tip.label))){
    traits2[cladesTree[[i]]$tip.label]<-1
  }else{
    traits2[cladesTree[[i]]$tip.label]<-0
  }
  if (length(grep("Aech",cladesTree[[i]]$tip.label))>length(grep("Ains",cladesTree[[i]]$tip.label))){
    traits3[cladesTree[[i]]$tip.label]<-1
  }else{
    traits3[cladesTree[[i]]$tip.label]<-0
  }
  
}
# add subfam as trait



plot(cladeSizes)
abline(h=11,col="red",lwd=2)


subfamTraits<-list()
for (i in levels(subfam$V2)){
  subfamTraits[[i]]<-rep(NA,length(t1$tip.label))
  names(subfamTraits[[i]])<-t1$tip.label
  subfamTraits[[i]]<-as.numeric(names(subfamTraits[[i]]) %in% unlist(subset(subfam,V2==i,V1)))
  names(subfamTraits[[i]])<-t1$tip.label
}

#traitsAll<-data.frame(cbind(traits,traits2,traits3,traits4,traits5))
traitsAllSubfam<-data.frame(do.call(cbind, subfamTraits))

#traitsAll2<-merge(traitsAll,subfam,by.x="row.names",by.y="V1")[,2:5]
#colnames(traitsAll2)[4]<-"subfam"
#row.names(traitsAll2)<-row.names(traitsAll)
#head(traitsAll2)

subfamTraitsPlot<-list()
for (i in colnames(traitsAllSubfam)){
  subfamTraitsPlot[[i]]<-c("white","red")
}
```

```{r}

#par(mai=c(2,2,2,2))
#trait.plot(t1,traitsAll ,list(traits = c("gray70", rgb(1,0,0,1)),traits5 = c("gray80", rgb(1,.1,0,1)),traits4 = c("gray90", rgb(1,.1,.1,1))),cex.lab = .0001,w=.2,margin=1)
trait.plot(t1,traitsAllSubfam,subfamTraitsPlot,cex.lab = .0001,w=.2,margin=1)
#dev.print(pdf,"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/results/tree/ORtree.pdf",width=20,height=20)

```
```{r}
# ggtree
library(RColorBrewer)
source("~/sciebo/librarySchrader.R")
```


```{r}
plotSF<-subfam$V2
names(plotSF)<-subfam$V1
t1000<-merge(data.frame(plotSF),data.frame(traits3),by="row.names")
row.names(t1000)<-t1000$Row.names
t1000<-t1000[,2:3]
t1000$traits3<-as.factor(t1000$traits3)
```

```{r}
tree_plot <- 
  ggtree(tr = t1, 
         layout  = 'circular',
         # set line thikness
         size = .2,ladderize = T
          ) 
tree_plot2 <- gheatmap(tree_plot,t1000[,"plotSF", drop=F] , offset = 0, width=.1, font.size=.1, colnames_angle=-45, hjust=0,color=NA) + scale_fill_manual(values=c(goodCols2,"red"))

tree_plot3 <- gheatmap(tree_plot2,t1000[,"traits3", drop=F] , offset = 1, width=.1, font.size=.1, colnames_angle=-45, hjust=0,color=NA) 

col <- c(rep(c("gray80","gray70"),13),"gray80", brewer.pal(4, "Pastel1")[1:2])
names(col) = c(letters[1:27], letters[1:2])
pp <- tree_plot3 + scale_fill_manual(values=col)

#names(col) = c(letters[1:29])
#https://bioconductor.statistik.tu-dortmund.de/packages/3.5/bioc/vignettes/ggtree/inst/doc/advanceTreeAnnotation.html
#geom_strip
#https://groups.google.com/forum/#!topic/bioc-ggtree/WkxI0r7x098
```

```{r} 
pp
dev.print(pdf,"/Users/lukas/sciebo/inquilineGenomics18/ORevolution/results/tree/ggORtree.pdf",width=20,height=20)
```


```{r}
library("ggplot2")
library("ggtree")

nwk <- system.file("extdata", "sample.nwk", package="treeio")

tree <- read.tree(nwk)
circ <- ggtree(tree, layout = "circular")

df <- data.frame(first=c("a", "b", "a", "c", "d", "d", "a", "b", "e", "e", "f", "c", "f"),
                 second= c("z", "z", "z", "z", "y", "y", "y", "y", "x", "x", "x", "a", "a"))

rownames(df) <- tree$tip.label


p1 <- gheatmap(circ, df[, "first", drop=F], offset=.8, width=.1,
               colnames_angle=90, colnames_offset_y = .25)
p2 <- gheatmap(p1, df[, "second", drop=F], offset=5, width=.1,
               colnames_angle=90, colnames_offset_y = .25)

require(RColorBrewer)
col <- c(brewer.pal(5, "Dark2"), brewer.pal(4, "Pastel1"))
names(col) = c(letters[1:6], letters[24:26])

pp <- p2 + scale_fill_manual(values=col)

p1x <- p1 + scale_fill_manual(values=col)
p2x <- gheatmap(circ, df[, "second", drop=F], offset=5, width=.1) +
    scale_fill_manual(values=col) 

require(cowplot)
leg1 <- get_legend(p1x)
leg2 <- get_legend(p2x)

pp <- pp + theme(legend.position="none")
plot_grid(pp, leg1, leg2, ncol=3, rel_widths=c(1, .1, .1))
```


```{r}
library("ggplot2")
library("ggtree")
nwk <- system.file("extdata", "sample.nwk", package="treeio")

tree <- read.tree(nwk)
circ <- ggtree(tree, layout = "circular")

df <- data.frame(first=c("a", "b", "a", "c", "d", "d", "a", "b", "e", "e", "f", "c", "f"),
                 second= c("z", "z", "z", "z", "y", "y", "y", "y", "x", "x", "x", "a", "a"))

rownames(df) <- tree$tip.label


p1 <- gheatmap(t1, t1000[,"plotSF", drop=F], offset=.8, width=.1,
               colnames_angle=90, colnames_offset_y = .25)
p2 <- gheatmap(p1, t1000[,"traits3", drop=F], offset=5, width=.1,
               colnames_angle=90, colnames_offset_y = .25)

require(RColorBrewer)
col <- c(brewer.pal(5, "Dark2"), brewer.pal(4, "Pastel1"))
names(col) = c(letters[1:6], letters[24:26])

pp <- p2 + scale_fill_manual(values=col)

p1x <- p1 + scale_fill_manual(values=col)
p2x <- gheatmap(circ, df[, "second", drop=F], offset=5, width=.1) +
    scale_fill_manual(values=col) 

require(cowplot)
leg1 <- get_legend(p1x)
leg2 <- get_legend(p2x)

pp <- pp + theme(legend.position="none")
plot_grid(pp, leg1, leg2, ncol=3, rel_widths=c(1, .1, .1))
```

