---
title: "Inquiline Genomics: analysis and summary of RELAX (results3)"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: true
    number_sections: true
    df_print: paged
  pdf_document: default
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>

# Introduction
We tested for relaxed selection in any social parasite branch.

# Input data 
### Load environment
```{r}
#install.packages("rjson")
library("rjson")
library(plyr)
library(tidyr)
library(ggplot2)
```

### Locate data
```{r}


# All parasite branches vs hosts & internal Acromyrmex branches (A1 & A2), Full Model
folder<-"/Users/lukas/sciebo/inquilineGenomics18/SOS/RELAX/results3/"

files<-dir(folder,pattern =".json")
```

### Retrieve branch wide dN/dS estimates for all SCOs
```{r}

pval<-NA
k<-NA
dNref<-NA
dNtest<-NA
OGs<-NA
results<-list()

branchNames<-list()
# loop over json file from each SCO and retrieve data. Store data in data frames 
for (q in 1:length(files)){
  OG<-gsub(pattern="(OG[0-9]{7})\\..*","\\1",perl=T,x=files[q])
  OGs[q]<-OG
  result <- fromJSON(file = paste(folder,files[q],sep=""))
  results[[q]]<-result
  pval[q]<- result$`test results`$`p-value`
  k[q]<-    result$`test results`$`relaxation or intensification parameter`
  dNref[q]<-result$fits$`MG94xREV with separate rates for branch sets`$`Rate Distributions`[[1]][[1]][1]
  dNtest[q]<-result$fits$`MG94xREV with separate rates for branch sets`$`Rate Distributions`[[2]][[1]][1]
  branchNames[[q]]<-names(result$`branch attributes`$`0`)
}  

#result$fits$`RELAX null`$`Rate Distributions`$Test
#result$fits$`RELAX null`$`Rate Distributions`$Reference
# branch names
#bn <- data.frame(do.call("rbind", branchNames))
```

```{r}
# get k
#results[[1]]$`branch attributes`$`0`$P1$`k (general descriptive)`

splitResults<-lapply(results, function(x) x$`branch attributes`$`0`) 
branchK<-unlist(lapply(splitResults, function(x) unlist(lapply(x,function(p) p$`k (general descriptive)` ))))
names(branchK)<-substr(names(branchK),1,4)
bdf<-data.frame(log(branchK,2))
colnames(bdf)[1]<-"branchK"
bdf$branch<-as.factor(names(branchK))
bdfL<-split(bdf,f=bdf$branch)
boxplot(bdfL[[1]]$branchK,bdfL[[2]]$branchK,bdfL[[3]]$branchK,bdfL[[4]]$branchK,bdfL[[5]]$branchK,bdfL[[6]]$branchK,bdfL[[7]]$branchK,bdfL[[8]]$branchK,bdfL[[9]]$branchK,names=names(bdfL)[1:9],outline=F,ylim=c(-10,10))
wilcox.test(bdfL[[9]]$branchK,bdfL[[5]]$branchK)
wilcox.test(bdfL[[1]]$branchK,bdfL[[3]]$branchK)
```
```{r fig.height=4, fig.width=5}
source("~/sciebo/librarySchrader.R")
plot(density(bdfL[[1]]$branchK),col=1,ylim=c(0,.4))
for(i in 2:9){
points(density(bdfL[[i]]$branchK),col=goodCols[i],type="l")
text(x = -30,y=.15*(i/4),names(bdfL)[i],col=goodCols[i])
}

abline(v=0,lwd=1,col="red",lty=2)
```

