---
title: 'CAFE kmeans clustering and plotting of results'
output:
  html_document:
    df_print: paged
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 8pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 8pt;
    height: 20px;
    font-weight: bold;
    text-align: right;
    background-color: #ccccff;
  }
  table { 
    border-spacing: 0px;
    border-collapse: collapse;
  }
--->
</STYLE>
```{r include=T}
nodeLabels<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/nodeLabels.tsv",sep="\t",header=F)
colnames(nodeLabels)<-c("tree","label")
```

```{r include=T}
###########################################################################
#K means clustering
###########################################################################

ratesRUN1<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/RUN1/treeRates.RUN1.tsv",sep="\t",skip=1,header=F)
ratesRUN2<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/RUN2/treeRates.RUN2.tsv",sep="\t",skip=1,header=F,nrows=10)

#rate<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/rates.CAFE.R2.tsv",sep="\t")
#rate<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/tmp/rates.CAFE.run4.tsv",sep="\t")
#rate<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/rates.RUN1.tsv",sep="\t")

colnamesRates<-c("tree","lambda1","lambda2","score","mu1","mu2","scoreTmp")
colnames(ratesRUN1)<-colnamesRates
colnames(ratesRUN2)<-colnamesRates
rate1<-merge(ratesRUN1,nodeLabels,all.x=T,all.y=T,by.x="tree",by.y="tree")
rate2<-merge(ratesRUN2,nodeLabels,all.x=T,all.y=T,by.x="tree",by.y="tree")

plot(as.matrix(rate1[2:nrow(rate1),c(3,6)]),col="red",pch=1,cex=2,xlab="lambda",ylab="mu",ylim=c(0,0.01),xlim=c(0,0.01))
points(as.matrix(rate2[2:nrow(rate2),c(3,6)]),col="black",pch=2,cex=2)
text(rate1$lambda2,rate1$mu2+.0005,rate1$label,cex=.6)

```


```{r include=FALSE}
# choose one of the runs as basis for analysis
rate<-rate2
#as.matrix(rate[2:nrow(rate),c(3,6)])
nmodels<-nrow(rate)
kclusters<-list()
for (i in 1:8){
  #kclusters[[i]]<-kmeans(as.matrix(rate[2:nmodels,c(3,6)]),i, algorithm = "MacQueen")
  #kclusters[[i]]<-kmeans(as.matrix(rate[2:nmodels,c(3,6)]),i, algorithm = "Hartigan-Wong")
  #kclusters[[i]]<-kmeans(as.matrix(rate[2:nmodels,c(3,6)]),i, algorithm = "Lloyd")
  kclusters[[i]]<-kmeans(as.matrix(rate[1:nmodels,c(3,6)]),i)
  
  
}
kclusters
rate$k1<-as.factor(c(kclusters[[1]]$cluster))
rate$k2<-as.factor(c(kclusters[[2]]$cluster))
rate$k3<-as.factor(c(kclusters[[3]]$cluster))
rate$k4<-as.factor(c(kclusters[[4]]$cluster))
rate$k5<-as.factor(c(kclusters[[5]]$cluster))
rate$k6<-as.factor(c(kclusters[[6]]$cluster))
rate$k7<-as.factor(c(kclusters[[7]]$cluster))
rate$k8<-as.factor(c(kclusters[[8]]$cluster))
#rate
```

```{r}
# alternative clustering approaches
library(fpc)
mydata<-as.matrix(rate[1:nmodels,c(3,6)])
row.names(mydata)<-rate$label[1:nmodels]
pamkResults<-pamk(mydata,3:9)
#plot( mydata[,1],mydata[,2] ,xlab="lambda",ylab="mu")
#text(x = mydata[,1],y=mydata[,2],labels=row.names(mydata))
d <- dist(mydata, method = "euclidean") # distance matrix
fit <- hclust(d, method="ward.D") 
plot(fit)
```

```{r echo=FALSE, fig.height=10, fig.width=10}
par(mfrow=c(4,2))
par(mai=c(.8,.8,0.1,0))
for (i in 1:8){
  modelLambda<-kclusters[[i]]$centers[,1]
  modelMu<-kclusters[[i]]$centers[,2]
  
  plot(rate$lambda2,rate$mu2,col="white",xlab=paste("lambda; Clusters=",i,sep=""),ylab="mu")
  text(paste(rate$label,rate[,8+i]),x=rate$lambda2,y=rate$mu2,cex=.8)
  text(1:i,x=modelLambda,y=modelMu,col="red",cex=2)
  
}

#write.table(rate,"/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/clustered.rates.CAFE.R1.tsv",quote=F, row.names=F,sep="\t")
```

I choose 5 clusters to go. 


```{r}

#(((3,(3,1)5)2,(4,5)2)2,2);
#(((AHEY,(ACHA,PARG)),(AECH,AINS)),ACOL);

RUN1C<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/RUN1C/rates.RUN1C.tsv",sep="\t",header=F)
RUN2C<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/RUN2C/rates.RUN2C.tsv",sep="\t",header=F)
RUN3C<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/CAFE/results/Acro.Atta/RUN3C/rates.RUN3C.tsv",sep="\t",header=F)


row.names(RUN1C)<-paste("r1c",1:length(RUN1C$V1),sep=".")
row.names(RUN2C)<-paste("r2c",1:length(RUN2C$V1),sep=".")
row.names(RUN3C)<-paste("r3c",1:length(RUN3C$V1),sep=".")
rates5cluster<-rbind(rbind(RUN1C,RUN2C),RUN3C)

rates5cluster
colnamesRates<-c("lambda1","lambda2","lambda3","lambda4","lambda5","score","mu1","mu2","mu3","mu4","mu5","scoreTmp")
colnames(rates5cluster)<-colnamesRates
rates5cluster<-rates5cluster[order(rates5cluster$score),]

renameRates<-cbind(rate[,c(8,13)],colnames(rates5cluster)[rate$k5])

lambda5cluster<-as.data.frame(t(rates5cluster))[1:5,]
mu5cluster<-as.data.frame(t(rates5cluster))[7:11,]

plot(lambda5cluster[,1],mu5cluster[,1],xlim=c(-0.0005,0.003),ylim=c(-0.0005,0.01),col="white")
for ( i in 1:5){
  text(lambda5cluster[,i],mu5cluster[,i],1:5,col=goodCols[i])
}

points(rate$lambda2,rate$mu2,col="red",cex=.4)
#text(rate$lambda2,rate$mu2,1:10,col="red",cex=1)

```

```{r fig.height=4.5, fig.width=3.1}
source("~/sciebo/librarySchrader.R")

dev.new(t,width=3.1,height=4.5)
#pdf("/Users/lukas/CSE/inquilineGenomics/geneFamilyEvolution/CAFE/TEfiltered/full/Clustering/ClusterM5bK.pdf",width=3.1,height=4.5)
par(mar=c(3, 3, 1, 1))
par(cex.lab=.8)
par(cex.axis=.6)
par(mgp=c(1.5,.4,0))


plot(rate$lambda2,rate$mu2,xlab="lambda; Clusters=5",ylab="mu",col=goodCols,pch=19,cex=1.2,xlim=c(-0.0005,0.003),ylim=c(-0.0005,0.008))

#rates5cluster
library(plotrix)
segments(x0 = rate$lambda2[rate$label=="PARG"],x1=lambda5cluster[1,1],y0=rate$mu2[rate$label=="PARG"],y1=mu5cluster[1,1],lty=1)
segments(x0 = rate$lambda2[rate$label=="AECH"],x1=lambda5cluster[4,1],y0=rate$mu2[rate$label=="AECH"],y1=mu5cluster[4,1],lty=1)
segments(x0 = lambda5cluster[3,1]+0.00027,x1=lambda5cluster[3,1],y0=mu5cluster[3,1]-0.00033,y1=mu5cluster[3,1],lty=1)
segments(x0 = lambda5cluster[5,1]+0.0001,x1=lambda5cluster[5,1],y0=mu5cluster[5,1]+0.0006,y1=mu5cluster[5,1],lty=1)

ellipseCol<-rgb(.95,.95,.95,1)
#draw.ellipse(lambda5cluster[1,1]+0.00005,mu5cluster[1,1]+0.0006,a=.0003,b=.00006,col=ellipseCol,angle=87,border="black")
draw.ellipse(lambda5cluster[2,1],mu5cluster[2,1]+0.00015,a=.0008,b=.00050,col=ellipseCol,angle=37,border=goodCols[1],lwd=4)
#draw.ellipse(lambda5cluster[4,1]+0.00074,mu5cluster[4,1]-0.0004,a=.0002,b=.0002,col=ellipseCol,angle=-60,border="black")
draw.ellipse(lambda5cluster[3,1]+0.0005,mu5cluster[3,1]-0.0002,a=.0004,b=.0006,col=ellipseCol,angle=-210,border=goodCols[2],lwd=4)
draw.ellipse(lambda5cluster[5,1]+0.00015,mu5cluster[5,1]+0.0006,a=.0009,b=.0004,col=ellipseCol,angle=50,border=goodCols[3],lwd=4)
points(lambda5cluster[,1],mu5cluster[,1],cex=.8,pch=3)

for(i in 1:nrow(rate)){
borCol<-"black"
points(rate$lambda2[i],rate$mu2[i],col=borCol,pch=19,cex=2.5)
if(rate$label[i]=="PARG"||rate$label[i]=="AECH"){
  points(rate$lambda2[i],rate$mu2[i],col=goodCols[3+i],pch=19,cex=3)
  }
points(rate$lambda2[i],rate$mu2[i],col="white",pch=19,cex=2)
text(x = rate$lambda2[i],y = rate$mu2[i],labels = i,cex=.6)
}
#text(x=rate$lambda2+0.00002,y=rate$mu2+0.0001,rate$label,cex=.4,pos=4,font=2)
#rates5cluster


```
```{r}
#LR test

library(extRemes)
# a = ln likelihood Score for the reduced model which omits the k predictors in question, and 
# b = ln likelihood Score for the current model which includes them. 
# df = k
#H0 = h0$ln[2]


lr.test(rate$score[1],rates5cluster$score[1])
lr.test(rates5cluster$score[2],rates5cluster$score[1])



```


```{r eval=FALSE, include=FALSE}
#M5bK model rates
modelLambda<-c(0.02284017,0.01232379,0.01291990,0.00194151,0.00206301)
modelMu<-c(0.02977765,0.01213601,0.03377317,0.04653597,0.00237993)

#assign nodes to cluster
rate$M5bK<-c(0,0,2,1,5,3,1,4,5,5,5,5,5,5)

CentL<-rep(NA,5)
CentM<-rep(NA,5)
CentL[1]<-mean(rate$Lambda[c(4,7)])
CentM[1]<-mean(rate$Mu[c(4,7)])
CentL[5]<-mean(rate$Lambda[c(5,9:14)])
CentM[5]<-mean(rate$Mu[c(5,9:14)])
CentL[2]<-rate$Lambda[rate$M5bK==2]
CentM[2]<-rate$Mu[rate$M5bK==2]
CentL[3]<-rate$Lambda[rate$M5bK==3]
CentM[3]<-rate$Mu[rate$M5bK==3]
CentL[4]<-rate$Lambda[rate$M5bK==4]
CentM[4]<-rate$Mu[rate$M5bK==4]

rate$M5bK<-c(NA,NA,2,1,5,3,1,4,5,5,5,5,5,5)

rate$CentersLambda<-rate$Lambda
rate$CentersLambda[1:2]<-NA
rate$CentersMu<-rate$Mu
rate$CentersMu[1:2]<-NA
rate$CentersLambda[rate$M5bK==1]<-CentL1
rate$CentersMu[rate$M5bK==1]<-CentM1
rate$CentersLambda[rate$M5bK==5]<-CentL5
rate$CentersMu[rate$M5bK==5]<-CentM5

rate$ModelLambda<-NA
rate$ModelMu<-NA

for (i in 1:5){
	rate$ModelLambda[rate$M5bK==i]<-modelMu[i]
	rate$ModelMu[rate$M5bK==i]<-modelLambda[i]
}


#dev.new(t,width=3.1,height=4.5)
dev.new(t,width=3.1,height=4.5)
#pdf("/Users/lukas/CSE/inquilineGenomics/geneFamilyEvolution/CAFE/TEfiltered/full/Clustering/ClusterM5bK.pdf",width=3.1,height=4.5)
par(mar=c(3, 3, 1, 1))
par(cex.lab=.8)
par(cex.axis=.6)
par(mgp=c(1.5,.4,0))

library(plotrix)
cols<-rgb(0,.2,.8,.2)

plot(rate$Lambda[2:15],rate$Mu[2:15],xlab="lambda",ylab="mu",cex=2,col="white",pch=1,xaxt="n",yaxt="n",xlim=c(0,0.034),ylim=c(0,0.06))
axis(2,at=seq(0,0.06,length=4),cex.lab=.5)
axis(1,at=seq(0,0.03,length=4),cex.lab=.5)
segments(modelLambda,modelMu,CentL,CentM)
points(modelLambda,modelMu,cex=.1)
points(modelLambda,modelMu,cex=.7)
draw.ellipse(mean(rate$Lambda[c(5,9:14)])+0.0003,mean(rate$Mu[c(5,9:14)])+0.001,a=.012,b=.0025,col=cols[1],angle=87,border=cols[1])
draw.ellipse(mean(rate$Lambda[c(4,7)]),mean(rate$Mu[c(4,7)]),a=.0056,b=.0025,col=cols[1],angle=77,border=cols[1])

points(rate$Lambda[3],rate$Mu[3],col=cols[1],cex=4,pch=19)
points(rate$Lambda[6],rate$Mu[6],col=cols[1],cex=4,pch=19)
points(rate$Lambda[8],rate$Mu[8],col=cols[1],cex=4,pch=19)
for (i in 2:15){
	points(rate$Lambda[i],rate$Mu[i],cex=1.8,col="white",pch=19)
	points(rate$Lambda[i],rate$Mu[i],cex=1.8,col="black",pch=1)
}
text(rate$Lambda[2:15],rate$Mu[2:15],seq(1:12),cex=.4)
segments(modelLambda,modelMu,CentL,CentM,col=rgb(0,0,0,.1))
points(modelLambda,modelMu,cex=.1,col=rgb(0,0,0,.1))
points(modelLambda,modelMu,cex=.7,col=rgb(0,0,0,.1))


draw.ellipse(mean(rate$Lambda[c(5,9:14)])+0.0003,mean(rate$Mu[c(5,9:14)])+0.001,a=.0123,b=.0028,col=rgb(0,0,0,0),angle=87,border="gray",lwd=3)
draw.ellipse(mean(rate$Lambda[c(4,7)]),mean(rate$Mu[c(4,7)]),a=.00563,b=.0027,col=rgb(0,0,0,0),angle=77,border="red",lwd=3)
points(rate$Lambda[3],rate$Mu[3],col="blue",cex=4,pch=1,lwd=3)
points(rate$Lambda[6],rate$Mu[6],col="black",cex=4,pch=1,lwd=3)
points(rate$Lambda[8],rate$Mu[8],col="darkgreen",cex=4,pch=1,lwd=3)



shiftx<-c(-0.0008,-0.0002,0.0001,0.0001,0.0015)
shifty<-c(-0.001,0.0005,0.0005,0.0005,0.0005)
for (i in 1:5){

	text(modelLambda[i]+shiftx[i],modelMu[i]-shifty[i],paste("x: ",round(modelLambda[i],4),"\ny: ",round(modelMu[i],4),sep=""),cex=.4,pos=4)
}
#dev.off()

#LR test

library(extRemes)
# a = ln likelihood Score for the reduced model which omits the k predictors in question, and 
# b = ln likelihood Score for the current model which includes them. 
# df = k

M<-read.csv("/Users/lukas/CSE/inquilineGenomics/geneFamilyEvolution/doc/tables/KmeansClustered.tsv",sep="\t")
h0<-read.csv("/Users/lukas/CSE/inquilineGenomics/geneFamilyEvolution/doc/tables/branchSpecRates.tsv",sep="\t")

#H0 = h0$ln[2]

lr.test(h0$ln[2],M$Score[1],df=2)
lr.test(h0$ln[2],M$Score[7],df=8)
lr.test(M$Score[6],M$Score[7],df=0)

```

