data<-read.csv("/Users/lukas/sciebo/inquilineGenomics18/geneFamilies/MCLclustering/Acro+Acol/finalQC.I01.5.tsv",sep="\t")
m<-data[,2:7]
plot(hclust(dist(t(m))))
dim(data)
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==1*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==2*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==3*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==4*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==5*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==6*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==7*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==8*6))
dim(subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==9*6))

subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==5*6,Best)
subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==6*6,Best)
subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==7*6,Best)
subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==8*6,Best)
subset(data,ACHA==ACOL & ACHA==AECH & ACHA==AHEY & ACHA==AINS & ACHA==PARG & FamSize ==9*6,Best)
par(mfrow=c(2,3))
par(mai=c(.6,.8,.1,.1))
plot(data$ACHA~data$ACOL,cex=.2)
text(10,50,round(summary(lm(data$ACHA~data$ACOL))$coefficients[2,1],4),col="red")
plot(data$AHEY~data$ACOL,cex=.2)
text(10,50,round(summary(lm(data$AHEY~data$ACOL))$coefficients[2,1],4),col="red")
plot(data$PARG~data$ACOL,cex=.2)
text(10,50,round(summary(lm(data$PARG~data$ACOL))$coefficients[2,1],4),col="red")
plot(data$AINS~data$ACOL,cex=.2)
text(10,50,round(summary(lm(data$AINS~data$ACOL))$coefficients[2,1],4),col="red")
plot(data$AECH~data$ACOL,cex=.2)
text(10,50,round(summary(lm(data$AECH~data$ACOL))$coefficients[2,1],4),col="red")



dim(subset(data,FamSize >=100))
subset(data,ClusterID=="Cluster31")